# Generated by Django 4.1.5 on 2023-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
