# Generated by Django 4.1.5 on 2023-02-04 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_users_ip_users_mac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='users',
            name='comments',
            field=models.BooleanField(default=False, verbose_name='التعليفات'),
        ),
        migrations.AlterField(
            model_name='users',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الالكتروني '),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'famle')], default='m', max_length=15, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الأي بي'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمن'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='حالة الحضر'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الماك'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='users',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='الاشعارات'),
        ),
        migrations.AlterField(
            model_name='users',
            name='private',
            field=models.BooleanField(default=False, verbose_name='الخاص'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='-', max_length=25, verbose_name='الحالة'),
        ),
    ]
