# Generated by Django 4.1.6 on 2023-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_users_options_alter_users_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='notification',
            field=models.CharField(choices=[('no_alert', 'ايقاف الاشعارات'), ('just_icon', 'ايقونة فقط'), ('icon_image', 'ايقونة وصورة')], default='icon_image', max_length=15, verbose_name='الاشعارات'),
        ),
    ]
