# Generated by Django 4.1.5 on 2023-01-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Room_id',
            new_name='room_id',
        ),
    ]
