# Generated by Django 4.1.4 on 2023-01-16 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0003_rename_room_id_message_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
