# Generated by Django 4.1.5 on 2023-01-19 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomsapp', '0004_room_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='room_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='room_banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='room_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
