# Generated by Django 4.1.5 on 2023-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0005_room_admins_room_banned_users_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
