# Generated by Django 4.1.5 on 2023-02-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomsapp', '0009_rename_admins_room_admin_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',), 'verbose_name_plural': 'الدردشات '},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-id',), 'verbose_name_plural': 'الغرف'},
        ),
        migrations.AlterField(
            model_name='message',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأنشاء'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', verbose_name='المرفقات '),
        ),
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsapp.room', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin_users',
            field=models.ManyToManyField(blank=True, related_name='room_admins', to=settings.AUTH_USER_MODEL, verbose_name='المسؤلين'),
        ),
        migrations.AlterField(
            model_name='room',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='room_banned_users', to=settings.AUTH_USER_MODEL, verbose_name='الاعضاء المحضورين'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_owner', to=settings.AUTH_USER_MODEL, verbose_name='المؤسس'),
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=25, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رابط الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='room_users', to=settings.AUTH_USER_MODEL, verbose_name='الأعضاء'),
        ),
        migrations.CreateModel(
            name='Bans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=200, verbose_name='الغرفة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الاسم')),
            ],
            options={
                'verbose_name_plural': 'الاشخاص المحضوررين ',
                'ordering': ('-id',),
            },
        ),
    ]
