# Generated by Django 4.1.6 on 2023-02-14 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0010_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bans',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الحضر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bans',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الغرفة'),
        ),
    ]
